# Generated by Django 5.0.6 on 2024-05-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
                ('status', models.CharField(choices=[('em aberto', 'Em Aberto'), ('pendente', 'Pendente'), ('finalizado', 'Finalizado')], default='em aberto', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('tipo_solicitacao', models.CharField(choices=[('manutencao', 'Manutenção'), ('outra_opcao', 'Outra Opção'), ('mais_uma_opcao', 'Mais Uma Opção')], default='manutencao', max_length=20)),
                ('prioridade', models.CharField(choices=[('minima', 'Mínima'), ('maxima', 'Máxima')], default='minima', max_length=20)),
            ],
            options={
                'db_table': 'dados_solicitacoes',
            },
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='prefeitura',
            new_name='register_prefeitura',
        ),
    ]
